language: php

php:
  - '7.3'
  - '7.4'

before_install:
  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN
  - composer config github-oauth.github.com $GITHUB_OAUTH_TOKEN

install: composer install --no-interaction

matrix:
  fast_finish: true

script:
  - ./build/runtests.bash
